name: K6 Load Test with HTML Report

on: [push]

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install k6-reporter
        run: npm install -g k6-reporter

      - name: Run k6 Load Test and Export Summary
        uses: grafana/k6-action@v0.2.0
        with:
          args: run --summary-export=summary.json test.js

      - name: Generate HTML Report
        run: k6-reporter summary.json -o result.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: k6-html-report
          path: result.html
